pipeline {
    agent any

    tools {
        // Install the Nodejs version configured as "nodejs" and add it to the path.
        nodejs "nodejs"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/MANOHAR452/node-hello.git'

                // Run Maven on a Unix agent.
                sh "npm install"
            }
        }
        stage('dockerbuild') {
            steps {
                sh "docker build . -t nodehello:${BUILD_NUMBER}"
            }
        }
        stage('dockerpush') {
            steps {
                script {
                    docker.withRegistry() {
                        docker.image().push()
                    }    
                }    
            }    
    }
}
